### ISSUE TITLE
Publish new App version to f-droid and Playstore

### ISSUE THREAD

**Issue by romedius** [fixme-lausanne/MyHackerspace#67]
Cool people committed cool patches and those should go live :)
The last published version is 1,5 years old.
(if help is needed, get in touch with me)

**Comment by dbrgn** [comment]
@rorist I'd be willing to update the app so it builds against the latest SDKs, and also to add SpaceAPI version 0.14 support.

Would you be willing to accept those, and to publish a new version of the app?

**Comment by rorist** [comment]
Hello, 

yes for sure ! I don't know if it will be simple to port the app the the new sdk's, I'm totally rusty with Android, but feel free to give it a try and send a PR.

Adding support for a new version should be as simple as adding a class [1] and modifying the loader [2].

[1] https://github.com/fixme-lausanne/MyHackerspace/blob/master/app/src/main/java/ch/fixme/status/Parse13.java
[2] https://github.com/fixme-lausanne/MyHackerspace/blob/master/app/src/main/java/ch/fixme/status/ParseGeneric.java#L70

**Comment by dbrgn** [comment]
Would increasing the min SDK level from 14 (Android 4.0) to 19 (Android 4.4) be OK for you? That would make many things easier. Those Android versions have not received any security updates in a loooong time and should not be used anyways. 21 (Android 5 Lollipop) would be even better, but that depends on what versions current users are on.

(In case you want to see current usage, there is a device version screen in the Google Play backend.)

**Comment by rorist** [comment]
Sure, the lowest installed version is 4.4 for 4 devices, then 10 ppl using 5.x.

**Comment by dbrgn** [comment]
Ok, I think then using 5.0 as minSdkTarget should be safe. The people using the current app on 4.4 can continue to do so.

**Comment by dbrgn** [comment]
Target SDK version is updated and CI is fixed! I plan to do some more cleanup (and maybe some UI improvements), afterwards a new release could be created :slightly_smiling_face:

**Comment by romedius** [comment]
Hi!
It's me again :)
Seems like the app is still not published yet. And our hackerspace has changed to the url which is available on soaceapi.io, bot not on the old spaceapi.net url anymore.
@dbrgn could you do an update or may I assist?

**Comment by dbrgn** [comment]
Check out the fork 🙂

https://github.com/spaceapi-community/my-hackerspace

For some reason, the app doesn't seem listed on Google Play anymore 😕 I'll have to investigate (and should submit to Fdroid as well).

**Comment by rorist** [comment]
I will remove my old version from the store when yours is back, it only adds confusion.

**Comment by dbrgn** [comment]
![screenshot-20220727-000608](https://user-images.githubusercontent.com/105168/181120583-2839cfd0-0642-4d1b-9b70-bae9a5648994.png)

WTF google... apparently email for that account wasn't being forwarded, and I never saw the notifications 😕

I'll try to reupload the app somehow, but might take a few days. Or maybe we'll only upload to F-Droid (and publish APKs) and skip Google Play 😕

**Comment by dbrgn** [comment]
> I will remove my old version from the store when yours is back, it only adds confusion.

that would be nice. although it would be even better if we could push a last update that indicates how to switch to the new app 🙂 if I find time I can prepare something.

**Comment by dbrgn** [comment]
FYI, I resubmitted the forked version to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11468

**Comment by niccokunzmann** [comment]
@dbrgn I have a google developer account you could use.

**Comment by dbrgn** [comment]
@niccokunzmann thanks for the offer! I'd rather keep things cleanly separated and set up a new account for SpaceAPI 🙂 (we had one before, I just messed up the forwarding of e-mails, that's why it was terminated.)
